### ISSUE TITLE
usosqueue - update for all users in users collection

### ISSUE THREAD

**Issue by smola222** [dzizes/usosapi#11]

**Comment by dzizes** [comment]
Hej!

    except Exception, ex:
        print ex.message
        return
else:
    try:


wprowadziliśmy logowanie, więc printów już nie robimy
jak łapiesz to lepiej wiedziec co zrobic z wyjatkiem, robienie return jest
niebezpieczne, bo nie wiesz co z danymi się zrobiło

sugeruję napisać metodę, bądź kilka metod w mongo_utils, coś na wzór: def
insert(self, collection, document):

która sprawdzi czy moze zainsertować, a jak nie mozę to zrobi update

wtedy w UsosQueue.crawl zmienisz tylko nazwę metody z insert na coś nowego
i będzie trzeba wprowadzać obsługi wyjątków

FriendsSuggestionsApi

tam wszystko było w ok. zwracana była lista, a nie słownik, zobacz
HtmlHelper.js który pracuje na listach, więc gdzie się da to listy
przekazujemy - wycofaj to proszę

to samo dotyczy usosapi/handlers/handlers_api_terms.py - to działało, nie
trzeba zmieniać i pisać na nowo. wszystko razem z wyświetlaniem grało,
teraz kod jest po raz kolejny inny i bardziej skomplikowany

except Exception, e:
    pass    # TODO: return json with custom message


jaki masz pomysł na realizację tego TODO?

---
Explicit is better than implicit.

**Comment by smola222** [comment]
done

**Comment by dzizes** [comment]
Do poprawy
