### ISSUE TITLE
login through Google account ouath

### ISSUE THREAD

**Issue by smola222** [dzizes/usosapi#22]

**Comment by dzizes** [comment]
init https://github.com/dzizes/usosapi/commit/93b46aa8ad2d1e4513629f639b23f4779717298f

after 1 login using google need to authenticate in USOS. how?

**Comment by smola222** [comment]
crowler sie wywala na:

yield self.__build_terms(user_id, usos, crowl_time)

i nie wiem dlaczego….

Wojciech Smołkowski
wojciech.smolkowski@gmail.com
