### ISSUE TITLE
handlers_api_friends.py", line 67, in get constants.USOS_ID: parameters[constants.USOS_ID]}) KeyError: 'usos_id'

### ISSUE THREAD

**Issue by dzizes** [dzizes/usosapi#40]
Exception while retrieving data: Traceback (most recent call last): File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\web.py", line 1401, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\web.py", line 1613, in future_complete f.result() File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\concurrent.py", line 232, in result raise_exc_info(self._exc_info) File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\gen.py", line 1017, in run yielded = self.gen.send(value) File "C:/Users/smolkows/PycharmProjects/usosapi/usosapi\handlers\handlers_api_friends.py", line 67, in get constants.USOS_ID: parameters[constants.USOS_ID]}) KeyError: 'usos_id'

**Comment by smola222** [comment]
po wyczyszczeniu bazy nie umiem takiego błedu powtórzyć.
