### ISSUE TITLE
school/grades 404

### ISSUE THREAD

**Issue by dzizes** [dzizes/usosapi#5]

**Comment by smola222** [comment]
wszysko sie rozjechało i nic nie dziala, nawet testy nie przechodzą. Super

Wojciech Smołkowski
wojciech.smolkowski@gmail.com

**Comment by dzizes** [comment]
Jest błąd na testy i będzie naprawiony jak znajdę czas

Trzeba wszystkie testy przepisać bo są teraz złe zrobione

**Comment by dzizes** [comment]
https://github.com/dzizes/usosapi/commit/e846ebd876b18aa5d32e6287ec863e5968960d54
