### ISSUE TITLE
constants id unifications

### ISSUE THREAD

**Issue by dzizes** [dzizes/usosapi#6]
USOS_ID = 'usos'
USER_USOS_ID = 'usos_id'

**Comment by smola222** [comment]
to jest według mnie dobrze nazwane, po co to zmieniac?

Wojciech Smołkowski
wojciech.smolkowski@gmail.com

**Comment by dzizes** [comment]
Nie zgadzam się 
Konwencja nazew nie jest zachowana

**Comment by smola222** [comment]
jak wedlug ciebie powinno byc? bo nie rozumiem - poprawie tak jak uwazasz.

**Comment by dzizes** [comment]
jeszcze nie udało ci się:
USOS_ID = 'usos'

powtarzam, powinno być:
USOS_ID = 'usos_id'
